
package whatizitws.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.transform.Source;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was jaxb.generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b59-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "whatizit", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws")
public interface Whatizit {


    /**
     * 
     * @param text
     * @param convertToHtml
     * @param pipelineName
     * @return
     *     returns java.lang.String
     * @throws WhatizitException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "contact", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws", className = "whatizitws.client.Contact")
    @ResponseWrapper(localName = "contactResponse", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws", className = "whatizitws.client.ContactResponse")
    public String contact(
        @WebParam(name = "pipelineName", targetNamespace = "")
        String pipelineName,
        @WebParam(name = "text", targetNamespace = "")
        String text,
        @WebParam(name = "convertToHtml", targetNamespace = "")
        boolean convertToHtml)
        throws WhatizitException_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<whatizitws.client.SelectItem>
     * @throws WhatizitException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPipelinesStatus", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws", className = "whatizitws.client.GetPipelinesStatus")
    @ResponseWrapper(localName = "getPipelinesStatusResponse", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws", className = "whatizitws.client.GetPipelinesStatusResponse")
    public List<SelectItem> getPipelinesStatus()
        throws WhatizitException_Exception
    ;

    /**
     * 
     * @param pmid
     * @param pipelineName
     * @return
     *     returns java.lang.String
     * @throws WhatizitException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryPmid", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws", className = "whatizitws.client.QueryPmid")
    @ResponseWrapper(localName = "queryPmidResponse", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws", className = "whatizitws.client.QueryPmidResponse")
    public String queryPmid(
        @WebParam(name = "pipelineName", targetNamespace = "")
        String pipelineName,
        @WebParam(name = "pmid", targetNamespace = "")
        String pmid)
        throws WhatizitException_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns javax.xml.transform.Source
     * @throws WhatizitException_Exception
     */
    @WebMethod
    @WebResult(name = "searchResponse", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws", partName = "parameters")
    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    public Source search(
        @WebParam(name = "search", targetNamespace = "http://www.ebi.ac.uk/webservices/whatizit/ws", partName = "parameters")
        Search parameters)
        throws WhatizitException_Exception
    ;

}
