//
// This file was sciverse.jaxb.generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.28 at 12:10:14 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://prismstandard.org/namespaces/basic/2.0/")
package org.prismstandard.namespaces.basic._2;
